---
- name: Install Additional Prerequisites
  package:
    name: "{{ item }}"
  loop: "{{ docker_additional_packages }}"

- name: Deploy Docker CE Repository  # noqa 305
  shell: "dnf config-manager --add-repo={{ docker_ce_repo_url }}"
  args:
    creates: "/etc/yum.repos.d/{{ docker_ce_repo_name }}.repo"
  when: ansible_os_family == "RedHat" and ansible_pkg_mgr == "dnf"

- name: Install pip
  package:
    name: "{{ docker_pip_package_name }}"

- name: Install Docker SDK
  pip:
    name: "{{ docker_sdk_package_name }}"

- name: Install Docker
  package:
    name: "{{ docker_ce_package_name }}"
    state: "{{ docker_package_state }}"

- name: Install Docker Compose
  pip:
    name: "{{ docker_compose_package_name }}"
  when: docker_install_docker_compose
