---
- name: Restart Docker  # noqa 503
  service:
    name: "{{ docker_service_name }}"
    state: restarted
  when: docker_daemon_config.changed

- name: Start Docker Service
  service:
    name: "{{ docker_service_name }}"
    state: started
  when: docker_service_enabled
    or (docker_registry_username and docker_registry_password)

- name: Enable Docker Service
  service:
    name: "{{ docker_service_name }}"
    enabled: "{{ docker_service_enabled }}"
