---
- name: Get local users
  getent:
    database: passwd

- name: Ensure group 'docker' exists
  group:
    name: docker

- name: Show if users are not present
  debug:
    msg: >
      User '{{ item }}' is not present on target,
      will not be created or added to group 'docker'
  loop: "{{ docker_users | difference(getent_passwd | flatten(levels=1)) }}"

- name: Add users to group 'docker'
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: item in getent_passwd | flatten(levels=1)
