---
- getent:
    database: passwd

- name: Ensure group 'docker' exists
  group:
    name: docker

- name: Add users to group 'docker'
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: item in getent_passwd | flatten(levels=1)
