---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: amazonlinux-2
    box: stakahashi/amazonlinux2
    memory: 512
    cpus: 1
    provider_options:
      gui: false
    provision: true
  - name: centos-7
    box: generic/centos7
    memory: 512
    cpus: 1
    provider_options:
      gui: false
    provision: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      stdout_callback: yaml
    diff:
      always: true
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  # provide a faster check sequence
  # => destroy has to be perfomed manualy
  check_sequence:
    - dependency
    - create
    - prepare
    - check
  # add check
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
